name: Azure Web App Container

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: AZ CLI Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUB_ID }}

      - name: Log in to ACR
        run: |
          az acr login -n ${{ secrets.ACR_NAME}}
      
      - name: Build and push container image to registry
        run: |
          docker build . -t https://${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.WEB_APP_NAME }}:${{ github.sha }}
          docker push https://${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.WEB_APP_NAME }}:${{ github.sha }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: AZ CLI Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUB_ID }}
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.WEB_APP_NAME }}
        slot-name: 'staging'
        images: ${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.WEB_APP_NAME }}/helloworld:${{ github.sha}}
        
  release:
    runs-on: ubuntu-latest
    needs: deploy
    
    steps:
    - name: AZ CLI Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUB_ID }}
    - name: Swap Staging Slot to Production
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az webapp deployment slot swap --slot 'staging' --name ${{ secrets.WEB_APP_NAME }} --resource-group ${{ secrets.WEB_APP_NAME }}
